alter table "public"."sentense" drop constraint "sentense_pkey";

drop index if exists "public"."sentense_pkey";

drop table "public"."sentense";

create table "public"."sentence" (
    "id" bigint generated by default as identity not null,
    "user_id" bigint,
    "story_id" bigint,
    "body" character varying,
    "created_at" timestamp with time zone default now()
);


alter table "public"."sentence" enable row level security;

CREATE UNIQUE INDEX sentense_pkey ON public.sentence USING btree (id);

alter table "public"."sentence" add constraint "sentense_pkey" PRIMARY KEY using index "sentense_pkey";


